name: Build and Push Chat Server Image

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-server:latest .
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            docker tag ${{ secrets.DOCKER_USERNAME }}/chat-server:latest ${{ secrets.DOCKER_USERNAME }}/chat-server:$VERSION_TAG
          fi

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-server:latest
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            docker push ${{ secrets.DOCKER_USERNAME }}/chat-server:$VERSION_TAG
          fi
